### PR TITLE
add Epicyon

### PR DESCRIPTION
**Pull request by bkil**
* ActivityPub based
* has follower-integrated calendar evetn function

### CODE REVIEW

**Comment by coderbyheart** [comment]
It's unclear to me from looking at the project's website, how they plan to provide a meetup alternative. Can you clarify this?

**Comment by bkil** [comment]
It has functionality similar to Friendica and Hubzilla: you can create either private or public events and your followers are also notified about your new events:
- https://blog.freedombone.net/epicyon-calendar

Friendica and Hubzilla also has a feature where you can RSVP for attendance, not sure if Epicyon already has such a thing implemented at the moment. But they do intend to use it in [FreedomBox](https://en.wikipedia.org/wiki/FreedomBox)/FreedomBone as well, and development seems to be active, they started more than a year ago:
- https://gitlab.com/bashrc2/epicyon/-/graphs/main

_edit: fixed link_

**Comment by bkil** [comment]
Maybe we should add a column with (predetermined) tags or a few words of description next to each entry?

I mean, consider that the best trendy meetup alternative seems to be Facebook, but the direction we're heading at is far from open source that way. We should better map out our options when viewed as a whole system.

**Comment by bkil** [comment]
So what do **you** consider a Meetup alternative, what is your definition and what are your use cases?

**Comment by bkil** [comment]
Hello. Thanks for merging. 

Actually, a lot has happened in the last 2 years - I just cherry picked your commit on top. We should review all projects again for status - just found a few NXDOMAIN for example.

Overall, I'm the archivist type and I think it might be interesting to keep archive.org links to defunct projects as well, but it could be useful to create a new table for that. The age threshold that is required for being defunct is still open for debate, though.

At the same time, I propose that a few more useful metadata could be collected, such as the type of the software: centralized vs. federated.

**Pull request merged**
